### ISSUE TITLE
Wrong namespace for null_provider when implementing privacy API 

### ISSUE THREAD

**Issue by TheBryanOpen228** [wiris/moodle-tiny_wiris#16]
Hi team, While adding the **tiny_wiris** plugin to our sites, there was a problem detected by our CI/CD regarding the privacy provider implementation, specifically I got the following error from a PhpUnit test:
```
There was 1 failure:
1) core_privacy_privacy_provider_test::test_all_providers_compliant with data set “tiny_wiris” ('tiny_wiris', 'tiny_wiris\privacy\provider').
Failed asserting that false is true.
```
This test search the privacy class 'tiny_wiris\privacy\provider' exists in the component tiny_wiris. But i found the namespace from l_ib/editor/tiny/plugins/wiris/classes/privacy/provider.php_ is:
`namespace tinymce_tiny_mce_wiris\privacy;`

So that's probably why the class is not found.  Just changing the namespace to the Moodle standard in [Privacy API](https://moodledev.io/docs/4.4/apis/subsystems/privacy#implementation-requirements) solves the problem for me, like this:
`namespace tiny_wiris\privacy;`

**Comment by carla-at-wiris** [comment]
Hello @TheBryanOpen228,

Thank you for writing us regarding this issue! This is definitely something we have to change on our code. We will move it to the next step and let you know when it gets fixed. If you have any further issues, please feel free to contact us.
