### ISSUE TITLE
missing gpl statement in key files

### ISSUE THREAD

**Issue by danmarsden** [wiris/moodle-tiny_wiris#5]
https://github.com/wiris/moodle-tinymce6_wiris/blob/main/classes/plugininfo.php#L1

the Moodle GPL statement should appear at the top of your php files...

you have it on this file:
https://github.com/wiris/moodle-tinymce6_wiris/blob/main/version.php#L1-L15

but not the plugininfo.php file above.

**Comment by danmarsden** [comment]
also missing in https://github.com/wiris/moodle-tinymce6_wiris/blob/main/lang/en/tiny_wiris.php#L1 - but please check all your php files.

**Comment by raortegar** [comment]
Hi, 
I think this issue can be close, I see the Moodle GPL statement is implemented now.

**Comment by carla-at-wiris** [comment]
Thank you all for pointing the issue!

As mentioned, the Moodle GPL statement is now implemented. Any further issues, please feel free to contact us!
